# `343.2.1 NumPy Practice Assignment`

#### Task 1: Create a NumPy array using np.array() and specify the data type as 'int32'. Print the array and its data type. 

#### Create another NumPy array using np.array() with the data type as 'float64'. Print the array and its data type. 

In [6]:
import numpy as np 
cat = np.array([[33, 55, 4, 7], [55, 66, 6, 5]])
dtype = np.int32
print(cat)
print(dtype) 




[[33 55  4  7]
 [55 66  6  5]]
<class 'numpy.int32'>


In [7]:
import numpy as np 
fish = np.array([[70, 8, 9, 10], [12, 90, 0, 4]]) 
dtype = np.float64 
print(fish) 
print(dtype) 

[[70  8  9 10]
 [12 90  0  4]]
<class 'numpy.float64'>


#### `Task 2`: Create one-dimensional Numpy array containing the integers from 1 to 5. Print the array. 

#### Create a two-dimensional NumPy array (matrix) with the following values

In [ ]:
import numpy as np 
arr = ([1, 2, 3, 4, 5]) # Created a numpy array containing the integers from 1 to 5

print(arr)  

boy = ([1, 2, 3, 4, 5], [1, 2, 3, 4, 5]) # Created a two-dimensional NumPy array (matrix) with the following values

print(boy) 

[1, 2, 3, 4, 5]
([1, 2, 3, 4, 5], [1, 2, 3, 4, 5])


#### Task 3: Create two NumPy arrays arr1 and arr2 with any values of your choice. Perform element-wise addition, subtraction, multiplication, and division, between these arrays and print the results

#### Calculate the dot product between arr1 and arr2. Print the result. Use NumPy to calculate the mean, median, and standard deviation of arr1.

In [ ]:
import numpy as np  
arr1 = np.array([[8, 88, 888, 8888, 88888], [2, 22, 222, 2222, 22222]]) # Created two NumPy arrays 
arr2 = np.array([[1, 11, 111, 1111, 11111], [5, 55, 555, 5555, 55555]]) 

a = arr1 + arr2  # Performed element-wise addition  of the two arrays 
print(a) 

b = arr1 - arr2  # Performed subtraction of the two arrays 
print(b) 

c = arr1 * arr2  # Performed multiplication of the two arrays 
print(c) 

d = arr1 / arr2  # Performed division of the two arrays
print(d) 


[[    9    99   999  9999 99999]
 [    7    77   777  7777 77777]]
[[     7     77    777   7777  77777]
 [    -3    -33   -333  -3333 -33333]]
[[         8        968      98568    9874568  987634568]
 [        10       1210     123210   12343210 1234543210]]
[[8.  8.  8.  8.  8. ]
 [0.4 0.4 0.4 0.4 0.4]]


In [ ]:
import numpy as np  
arr12 = np.array([[8, 88, 888, 8888, 88888], [5, 22, 555, 2222, 55555]])  
arr22 = np.array([[1, 11, 111, 1111, 11111], [5, 22, 555, 2222, 55555]]) 

m = np.dot(arr12, arr22.T) # Calculated the dot product between arr1 and arr2 
print(m) # Printed the result 

[[ 997608680 4958416792]
 [ 619802099 3091603843]]


In [35]:
import numpy as np 
arr1 = np.array([[8, 88, 888, 8888, 88888], [2, 22, 222, 2222, 22222]]) 

flat_arr1 = arr1.flatten() #Flatten the array to a 1D list of numbers 

mean = np.mean(flat_arr1)  
median = np.median(flat_arr1) 
std_dev = np.std(flat_arr1) 

print("Mean:", mean) 
print("Median:", median) 
print("Standard Deviation:", std_dev) 

Mean: 12345.0
Median: 555.0
Standard Deviation: 26373.62987910462
